layers: [
  { "type": "conv", "channels": 32, "kernel": 5, stride: 4 },

  { "type": "conv", "channels": 32, "kernel": 1, stride: 1 },
  { "type": "skip", "channels": 32, "kernel": 3, stride: 1 },
  { "type": "hidden-pool", "kind": "max" },

  { "type": "skip", "channels": 32, "kernel": 3, stride: 1 },
  { "type": "hidden-pool", "kind": "max" },

  { "type": "conv", "channels": 64, "kernel": 1, stride: 1 },
  { "type": "skip", "channels": 64, "kernel": 3, stride: 1 },
  { "type": "hidden-pool", "kind": "max" },

  { "type": "conv", "channels": 128, "kernel": 1, stride: 1 },
  { "type": "skip", "channels": 128, "kernel": 3, stride: 1 },

  { "type": "global-pool", "kind": "mean" },
]
