train:
  _target_: src.data.TreeGenerator
  min_nodes: 6
  max_nodes: 9
  n_node_colors: 3
  n_edge_colors: 3
val:
  _target_: src.data.TreeGenerator
  min_nodes: 10
  max_nodes: 10
  n_node_colors: 3
  n_edge_colors: 3
max_node_degree: null
