epochs: 1_000
samples_per_epoch: 100
evals_per_epoch: 1
batch_size: 16
weight_decay: 0.0
lr: 1e-4
lr_cycle: 10_000
lr_warmup: 1_000
lr_factor: 10
max_grad_norm: null
cache_size: 100
cache_warmup: 10
image_size: 256
image_warmup: 1_000
label_smoothing: 0.0
